### ISSUE TITLE
should support customized schema prefix

### ISSUE THREAD

**Issue by kaktos** [douban/rexxar-android#11]
现在是在Constants.java里面写死了`CONTAINER_WIDGET_BASE = "douban://rexxar-container/widget"`，是不是可以提供一种定制化的。

**Comment by xuchaobei** [comment]
@kaktos 既然是常量，也可以看成是配置项，自己改成自己想要的就可以。

**Comment by qluan** [comment]
@kaktos  暂时不打算提供专门接口去改变`schema`，这并不是`Rexxar`提供的功能。

但为了使用方便，讲`schema`单独定义，并移除`final`, 可以尝试这样修改下。
