### ISSUE TITLE
如何处理两个H5页面的跳转？

### ISSUE THREAD

**Issue by xuchaobei** [douban/rexxar-android#17]
a.html 跳转到 b.html, 是通过拦截a.html中的跳转请求，在原生层中转换成以startActivity的方式去启动另一个Container吗？这样的话，H5页面的跳转协议是不是要写两套呢？在浏览中运行时是一套，在手机端中运行时是另一套？

希望能提供一个较复杂的示例参考。

**Comment by qluan** [comment]
@xuchaobei 如你所说，确实需要在a.html中拦截请求，然后在native层调用startActivity做跳转。

`H5页面的跳转协议是不是要写两套呢？在浏览中运行时是一套，在手机端中运行时是另一套` 这点不太理解，能否说的再详细些？

**Comment by xuchaobei** [comment]
@qluan 浏览器中运行时，a.html 跳转到 b.html 是通过类似history.push(b.html) 的方式；手机端运行时， 是通过拦截你们自定义的"douban://..." 协议，在native层调用startActivity做跳转。这两种方式的Gap很大，是否可以考虑都统一的采用浏览器中url的跳转协议来进行跳转呢？

**Comment by qluan** [comment]
@xuchaobei 

1. 是否可以考虑都统一的采用浏览器中url的跳转协议?

可以的。
app内每个页面的uri使用什么协议看个人习惯，即可以是自定义schema，也可以是`http` schema。
但是建议使用自定义schema的，如果web端也有相同的页面，可以也同时支持`http`协议。

2. 跳转方式：`history.push(b.html) ` 和 `native层调用startActivity` 

`Rexxar` 是用混合开发的方式快速实现一些页面，作用范围仅仅是单个页面甚至页面内的某个模块， 页面之间的跳转依然遵循nativie的跳转方式，不支持`history.push(b.html) ` 。
