### ISSUE TITLE
api拦截，如何得到post请求body

### ISSUE THREAD

**Issue by fanrry** [douban/rexxar-android#20]
麻烦问下，api拦截，如何得到post请求body？谢谢~

**Comment by qluan** [comment]
@fanrry 

`WebViewClient.shouldInterceptRequest()`只能拦截到请求的url，5.0以上可以拿到`headers`，原生是无法支持获取body的。

`Rexxar`在这块的做法是：web端将post的参数以`key-value`的形式跟在url后面，然后再添加一个参数`_rexxar_method`赋值为`POST`,  Rexxar-Android会自动将请求url后的参数转成Request.body供java层使用。但如果是复杂的body，比如图片，二进制就不支持了。 如果有类似需求，可以考虑转成base64传输，java层解析
