### ISSUE TITLE
Intercepter 添加 headers 信息不成功

### ISSUE THREAD

**Issue by ruanhaojian** [douban/rexxar-android#23]
你好，我在web端使用的是axios的一个ajax库，在android端希望通过添加headers信息来处理登录状态。可是服务器端并未能接收到headers的修改信息。

-------

测试发现fetch加headers是可以成功添加的。

请问是不支持ajax加headers吗？

**Comment by ruanhaojian** [comment]
补充：android如此，ios不会。

**Comment by qluan** [comment]
@ruanhaojian 

能否看下webview是否可以拦截到请求?

1. 开启debug

    ```
Rexxar.setDebug(true);
   ```

2. 查看log，tag: `RexxarWebViewClient`, 内容：`[handleResourceRequest] url =  xxxxx`

**Comment by ruanhaojian** [comment]
@qluan Android debugger 是显示已经添加的头信息的，可是服务器就是接收不到。我现在先换回用fetch了。

**Comment by ruanhaojian** [comment]
`ResourceProxy.getInstance().addProxyHosts(List<>() hosts);`  这个应该可以解决,晚点试一下。
