### ISSUE TITLE
可以方便定制使用 腾讯 X5 内核么？

### ISSUE THREAD

**Issue by xiaolongyuan** [douban/rexxar-android#26]

**Comment by qluan** [comment]
@xiaolongyuan 腾讯的x5内核替换了整个webview及周边基础设施，只能替换，很难定制或者兼容。如果有实际需要，建议fork一份

**Comment by xiaolongyuan** [comment]
按照教程 直接改  一堆错  汗

**Comment by xiaolongyuan** [comment]
目前这个支持 文件上传么？ demo 内容好像很简单

**Comment by qluan** [comment]
自带的webview不支持`file`标签，所以不支持文件上传
