### ISSUE TITLE
为何RexxarContainerAPI设计为全局有效？

### ISSUE THREAD

**Issue by promeG** [douban/rexxar-android#33]
目前无法对不同的RexxarWebViewClient实例设置不同的RexxarContainerAPI，请问是特意如此设计的吗？

目前在使用时遇到一些不便之处：

例如实际想请求的url为：http://xxx.com/detail.html?id=1 , 目前我采用的方式是使用rexxar打开http://xxx.com/detail.html , 然后通过RexxarContainerAPI传入id=1的参数。 http://xxx.com/detail.html 中的js脚本拿到id后再请求数据并显示。

请问上述使用方法是否符合rexxar的设计初衷？

如果是的话，可能对不同的RexxarWebViewClient实例设置不同的RexxarContainerAPI更加灵活一些。

如果我的使用方法有问题，请不吝赐教。

**Comment by lincode** [comment]
Rexxar 的设计里，没有考虑使用 html 地址直接定位一个页面。
Reexar 的设计里，需要一个 route 表。这个表中有 url 到 html 资源地址的映射关系。
一个例子是：https://raw.githubusercontent.com/douban/rexxar-web/master/example/dist/routes.json
你在将参数放在 uri 中，rexxar 支持简单的 uri 模式匹配。

需要这个路由表的原因很多。其实，是多了一层缓冲。
1 本质上，这是一个使用什么做页面的 identifier 的问题。我们大约可以保证一个页面的 uri 不变。当然，你也可以说你能保证 html 资源地址不变。但我们觉得 uri 不变似乎更恰当一些。
2 我们的 native 实现的页面其实也可以用 uri 定位。这样需要 rexxar 页面的 identifier 和 native 页面的 identifier 就具有一致的格式。

**Comment by lincode** [comment]
Rexxar 的 ContainerAPI 是一个协议，用于在 Rexxar Container 中扩展这样一种类型的API： native 计算的结果，但是由 web 消费。比如，设备的 GPS 信息。

**Comment by qluan** [comment]
@promeG  `RexxarContainerAPI设计为全局有效`存在一些场景不方便之处，已经提pr解决，已可以升级到 0.2.5

**Comment by promeG** [comment]
@qluan 谢谢！
